### ISSUE TITLE
provided script in zip doesn't work

### ISSUE THREAD

**Issue by unixandria-xda** [Magisk-Modules-Repo/dnscrypt-proxy2#10]
Iptables errors out with: 
```
Bad argument `!-d'
Try `iptables -h' or 'iptables --help' for more information.
```

Also, I'm not sure what the variables for ipv6 are supposed to be set to

**Comment by unixandria-xda** [comment]
First errors solved by putting space between ! and -d

**Comment by lindroidux** [comment]
updated, Thank you
