### ISSUE TITLE
URL not resolved on version 2.9.1

### ISSUE THREAD

**Issue by froz3n** [Magisk-Modules-Repo/dnscrypt-proxy2#4]
Been using 2.8.9 fine, but found the error on 2.9.1.
Probably because of bug on dnscrypt binary as the newest one, version 2.0.33, is working fine when I replace the binary manually.

**Comment by lindroidux** [comment]
Pls enable loglevel to 0 in dnscrypt-proxy.toml, restart dnscrypt-proxy by typing in terminal as root:
pkill -HUP dnscrypt-proxy
and post the log.

**Comment by froz3n** [comment]
Here https://drive.google.com/file/d/13hfMgdeyYvo0mBPp4gKMUR8V7K0kcMAG/view?usp=drivesdk

**Comment by lindroidux** [comment]
Either Comment  out blacklist_file in dnscrypt-proxy.toml or put a blank or populated blacklist.txt in dnscrypt-proxy directory
The issue is not related to binaries.

**Comment by froz3n** [comment]
That's where it is weird. I never enabled blacklist and it is still commented out. Latest binary does not throw that error too.

**Comment by lindroidux** [comment]
It was enabledby default during installation/upgraduation while the old dnscrypt-proxy.toml is backed up.

**Comment by froz3n** [comment]
I see. Now that I checked the latest zip, it is enabled by default. My manually created zip must be made using older setting file then, and I did not realized that there was a different.
