### ISSUE TITLE
Extra space on service.sh file

### ISSUE THREAD

**Issue by cypherpunk1984** [Magisk-Modules-Repo/dnscrypt-proxy2#6]
There is an extra space after "-config":

$MODDIR/system/bin/dnscrypt-proxy -config (HERE) /data/media....

It was making dnscrypt-proxy not detecting the config file on my phone, removing the extra space fixed it.

**Comment by lindroidux** [comment]
Thank u. Changes commited.
[https://github.com/Magisk-Modules-Repo/dnscrypt-proxy2/commit/4a8e9584c8c83485abed468f21cb8a046eefda52]
