### ISSUE TITLE
Android 10: Set localhost in settings or with AdAway?

### ISSUE THREAD

**Issue by Utini2000** [Magisk-Modules-Repo/dnscrypt-proxy2#7]
Hello everyone,

I was happy to see that in Android 10 you can finally set your own DNS server in the settings. 
How ever, only domains works (e.g. mydomain.abc) but you can't set a port or IP address.

I already use AdAway and I noticed that the dnscrypt-proxy2 description mentions that is it possible to set the DNS with e.g. DNS66 or DNSfilter. So I suspect it would also work with AdAway? That would mean I won't need another 3rd party app running additionally on my phone.

Could you guide me on how to set the localhost DNS server in AdAway or maybe there is a way to configure DNSCrypt to actually work with the standard port that the Android 10 settings are listening too? Then I could maybe try setting "localhost" as domain?

Thanks in advance!

**Comment by lindroidux** [comment]
I only know setting up this module using iptables (using afwall).

**Comment by Utini2000** [comment]
The readme says "DNS66 or dnsfilter app (both apps available in F-Droid repo) can also be used instead of custom script in AFWall."

I guess afwall is also using pretty much battery?

**Comment by lindroidux** [comment]
Dnscrypt-proxy is listening for dns request at IP address 127.0.0.1 port 5253.
The iptables command is used to redirect the dns requests, targetted for the default IP addresss/gateway listening at port 53, to 127.0.0.1:5253 (IP address127.0.0.1 is the localhost).

AFwall is only a front end for the iptables & consumes least battery.

AFwall is preferred because the phone has to be rooted by installing magisk, anyway.

**Comment by Utini2000** [comment]
Alright, thanks. I will give AFwall a try then. Maybe it comes in handy to also block some other apps internet connection.

**Comment by lindroidux** [comment]
In AFwall, allow internet access for UID 0 [root] Apps running as root
(todo:update Readme.MD

**Comment by Utini2000** [comment]
I also just saw this in the readme. Either I was blind or this is new. But it is awesome to see it now :-) 

A script file named dns-redirect.sh is included in the configuration directory. The file may be copied to /data/adb/service.d & its permission set to executable for auto-redirection of dns request (for those users not interested in using AFWall or other apps).

**Comment by lindroidux** [comment]
The advantage of AFwall is that it reloads the rules when switching between wifi & mobile data connection. Plus, the firewall..

**Comment by Utini2000** [comment]
Yes I am starting to like the idea of using AFwall. I am just very unsure if it is actually good (not just safe but also good) to block all those system and google services/modules/apps? I mean, they are probably there for a reason? Also, won't they try to frequently re-connect to the internet if they notice that they are "offline"? This could cause increase battery drain?

Screenshots:
https://files.bestmail.ws/afwall/12.jpg
https://files.bestmail.ws/afwall/photo_2020-07-20_00-11-45.jpg
https://files.bestmail.ws/afwall/photo_2020-07-20_00-11-47.jpg
https://files.bestmail.ws/afwall/photo_2020-07-20_00-11-48.jpg
