### ISSUE TITLE
DNSSEC not working, tons of resolves in dnsleaktest

### ISSUE THREAD

**Issue by Utini2000** [Magisk-Modules-Repo/dnscrypt-proxy2#8]
Hi there, 

I use the latest magisk module + afwall on Android 10 (Pixel 4 XL) with stock ROM.
I can't get DNSSEC to work with the module. Also when running dnsleaktest.com I get like 20 resolvers listed there.
I tried this module and it worked just fine: https://git.nixnet.xyz/quindecim/dnscrypt-proxy-android

Here is my .toml and my log files: https://files.bestmail.ws/logs.zip

AFWall Start Script:
iptables -t nat -A OUTPUT -p tcp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354
iptables -t nat -A OUTPUT -p udp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354

AFWall Stop Script:
iptables -t nat -D OUTPUT -p tcp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354
iptables -t nat -D OUTPUT -p udp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354

If I should provide anything else, please let me know. Thanks!

**Comment by lindroidux** [comment]
I donot see any issue with yr setup the logs except dnscrypt-proxy is not listening on ipv6.

You have query.log enabled in dnscrypt-proxy.toml, hence the resolved queries are available.

**Comment by Utini2000** [comment]
I tried those test. They do not validate.
Also dnsleaktest shows like 15 dns servers? Here is a screenshot with only a few but usually there are more listed:

![photo_2020-07-22_14-34-28](https://user-images.githubusercontent.com/14877663/88177038-80ce8e00-cc28-11ea-8800-5a6ece400b52.jpg)

Maybe there are somehow more dns servers active at the same time? And some of them might not have DNSSEC?

**Comment by Utini2000** [comment]
@lindroidux This is a better screenshot. That can't be normal? Usually it should only be 1 or 2 servers in that list?
![photo_2020-07-22_18-27-44](https://user-images.githubusercontent.com/14877663/88202401-1da12380-cc49-11ea-9303-28f947e1a7d7.jpg)

**Comment by lindroidux** [comment]
It is ok if the above list of servers are only those mentioned in public-resolvers.md

**Comment by Utini2000** [comment]
Really weird. I guess I have to go back to quindecim module. Just too bad it isn't on magisk for auto-updates.

**Comment by lindroidux** [comment]
The scope of DNSSEC in dnscrypt-proxy is as mentioned here:
(https://github.com/DNSCrypt/dnscrypt-proxy/issues/247)
