### ISSUE TITLE
Incomplete iptables commands (missing '! -d 1.1.1.1')

### ISSUE THREAD

**Issue by mherrmann3** [Magisk-Modules-Repo/dnscrypt-proxy2#9]
Thanks for reviving _dnscrypt-proxy2_ for Android!

Small thing: I noticed that the iptables' `nat` table gets populated with the same entries over time (check with `iptables -t nat -S OUTPUT`). The reason is that the `! -d 1.1.1.1` string is missing in the `iptables -t nat -D` commands. If you execute those, iptables complains: `No chain/target/match by that name`. I'm too amateur though to know if duplicate rules have any negative consequences.

Anyways, these would be correct:

    # First two lines delete current DNS settings 
    $IPTABLES -t nat -D OUTPUT -p tcp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354 || true 
    $IPTABLES -t nat -D OUTPUT -p udp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354 || true 

Note that this correction is also needed in your provided [`dns-redirect.sh`](https://github.com/Magisk-Modules-Repo/dnscrypt-proxy2/blob/master/config/dns-redirect.sh) script.

Keep up the good work!

**Comment by lindroidux** [comment]
Corrected/updated. Thank you. :-)

**Comment by mherrmann3** [comment]
Thanks! Minor typo in `dns-redirect.sh`, though: it should be `! -d` instead of `!-d` (notice the space). Currently it would not execute the commands because `!-d` has another meaning (alias for a command in the history).

Could you also set the exec permission of `dns-redirect.sh` for the owner so that AFWall+ can execute it as custom script? (something like `chmod 644 /data/media/0/dnscrypt-proxy/dns-redirect.sh`)

**Comment by lindroidux** [comment]
The typo has been corrected, Refers issue (https://github.com/Magisk-Modules-Repo/dnscrypt-proxy2/issues/10)

**Comment by lindroidux** [comment]
Since the dns-redirect.sh file is copied to the shared storage or sdcard, its permissions cannot be set to executable. The script would be executed by AFwall for each connection change [if 3dot menu->Preferences->Rules/Connectivity->Active rules is checked] and path of the script is entered [at 3dotmenu->Set custom script] for both "Enter custom script below" and "Custom shutdown script". The path should start with a dot and space.

e.g . /storage/emulated/0/dnscrypt-proxy/dns-redirect.sh

or
 /sdcard/0/dnscrypt-proxy/dns-redirect.sh

The exact path can be found in file managers like mixplorer.

**Comment by mherrmann3** [comment]
Hm, okay. I provided the path to `/data/media/dnscrypt-proxy/dns-redirect.sh` since AFWall+ has root anyway. When providing the location to the script with `/storage/...`, it doesn't execute ("Permission denied") - same result when specifying the location with `/data/...` but without the execution permission (of course). Dunno what is wrong on my system, but setting the execution permission *directly* to the script located under `/data/...` (i.e. with root) helped. That's what I meant before.

Anyways, are you sure that putting your script into the "Custom shutdown script" section of AFWall+ will remove the rule? Because the purpose of the script is to eventually add the rule to iptables. What you need here are only the commands with the `-D` argument.
